name: pack_and_go
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  animated_text_kit: null
  animation_list: ^3.1.0
  animations: null
  bottom_picker: ^2.9.0
  cached_network_image: ^3.3.1
  country_code_picker: ^3.1.0
  cupertino_icons: ^1.0.6
  dotted_border: ^2.1.0
  draggable_home: ^1.0.5
  dropdown_button2: ^2.3.9
  entry: null
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.2
  flutter_bounce: ^1.1.0
  flutter_slidable: ^3.1.1
  flutter_svg: null
  get: null
  google_fonts: null
  gradient_borders: ^1.0.1
  image_stack: ^2.1.1
  input_quantity: ^2.3.4
  intl: ^0.19.0
  pinput: ^5.0.0
  slide_action: null
  smooth_page_indicator: null
  story_view: ^0.16.5
  syncfusion_flutter_sliders: ^27.1.53
  table_calendar: ^3.1.2

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
  fonts:
    - family: Urbanist
      fonts:
        - asset: assets/fonts/Urbanist-Thin.ttf
          weight: 100
        - asset: assets/fonts/Urbanist-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Urbanist-Light.ttf
          weight: 300
        - asset: assets/fonts/Urbanist-Regular.ttf
          weight: 400
        - asset: assets/fonts/Urbanist-Medium.ttf
          weight: 500
        - asset: assets/fonts/Urbanist-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Urbanist-Bold.ttf
          weight: 700
        - asset: assets/fonts/Urbanist-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Urbanist-Black.ttf
          weight: 900

flutter_assets:
  assets_path: assets/
  output_path: lib/generated/
  filename: assets.dart
  field_prefix: null
